id: scene-001

threads: 6

# # Material with all properties set
# material:
#   baseColor: red               # required (can also be [r,g,b] or float/int values)
#   specularColor: white     # optional, defaults to `baseColor` if omitted
#   roughness: 0.2           # optional, default = 0.0
#   refractiveIndex: 1.5     # optional, default = 1.0
#   meanFreePath: 0.1        # optional, default = 0.0
#   radiance: 5.0           # optional, default = 0.0 (emission)
#   colorTexture: "texture.png"  # optional, default = no texture
#   useFresnel: true         # optional, default = true
  
#   # Optional: probabilities for interactions
#   probabilities:
#     diffuse: 0.5           # optional, default if not specified
#     reflective: 0.4        # optional, default if not specified
#     refractive: 0.1        # optional, default if not specified

render:
  image: true
  video: false
  video_duration: 2.0
  open_output_files: true

camera:
  renderer_type: RAY_TRACER # Options: SIMPLE, DETERMINISTIC, RAY_TRACER PATH_TRACER
  fov_deg: 120.0
  position: [9.0, 0.2, 0.0]
  direction: [-1.0, 0.0, 0.0]
  resolution:
    width: 800
    height: 600
  framesPerSecond: 15
  antialiasing: true
  blur_image: false
  samples_per_pixel: 1

scene:
  background_color: black
  objects:
    - type: Sphere
      id: ceiling-lamp
      visible: true
      position: [0.0, 0.0, 4.0]
      velocity: [0.0, 0.0, -2.0]
      radius: 1.0
      material:
        baseColor: white
        radiance: 1.0

    - type: Rectangle
      id: floor
      visible: true
      position: [0.0, 0.0, -5.0]
      normal: [0.0, 0.0, 1.0]
      dimensions:
        width: 20.0
        height: 20.0
      material:
        baseColor: blue

    - type: Rectangle
      id: right-wall
      visible: true
      position: [0.0, 10.0, 0.0]
      normal: [0.0, -1.0, 0.0]
      dimensions:
        width: 10.0
        height: 20.0
      material:
        baseColor: green

    - type: Rectangle
      id: left-wall
      visible: true
      position: [0.0, -10.0, 0.0]
      normal: [0.0, 1.0, 0.0]
      dimensions:
        width: 10.0
        height: 20.0
      material:
        baseColor: red

    - type: Rectangle
      id: ceiling
      visible: true
      position: [0.0, 0.0, 5.0]
      normal: [0.0, 0.0, -1.0]
      dimensions:
        width: 20.0
        height: 20.0
      material:
        baseColor: orange

    - type: Rectangle
      id: back-wall
      visible: true
      position: [-10, 0.0, 0.0]
      normal: [1.0, 0.0, 0.0]
      dimensions:
        width: 10.0
        height: 20.0
      material:
        baseColor: yellow

    - type: Rectangle
      id: front-wall
      visible: true
      position: [10, 0.0, 0.0]
      normal: [-1.0, 0.0, 0.0]
      dimensions:
        width: 10.0
        height: 20.0
      material:
        baseColor: cyan

    - type: Disk
      id: mirror-left
      visible: true
      position: [0.0, -9.99, 0]
      normal: [0.0, 1.0, 0.0]
      radius: 2.5
      material:
        baseColor: white
        probabilities:
          diffuse: 0.0
          reflective: 1.0
          refractive: 0.0

    - type: Sphere
      id: mirror-ball
      visible: true
      position: [0.0, 0.0, 0]
      radius: 2.0
      material:
        baseColor: white
        probabilities:
          diffuse: 0.0
          reflective: 1.0
          refractive: 0.0

    - type: Sphere
      id: glass-ball
      visible: true
      position: [3.0, 4.0, 0.0]
      radius: 2.0
      material:
        baseColor: white
        refractiveIndex: 1.5
        useFresnel: false
        probabilities:
          diffuse: 0.0
          reflective: 0.1
          refractive: 0.9

    - type: Sphere
      id: red-ball
      visible: true
      position: [-3.0, -4.0, -2.0]
      radius: 1.0
      material:
        baseColor: red

    - type: Cylinder
      id: corner-cylinder
      visible: true
      position: [-9.0, -9.0, 0.0]
      normal: [0.0, 0.0, 1.0]
      radius: 1.0
      height: 10.0
      material:
        baseColor: green

    - type: Cylinder
      id: small-cylinder
      visible: true
      position: [-6.0, 5.0, -3.0]
      normal: [1.0, 1.0, 1.0]
      radius: 1.0
      height: 2.0
      material:
        baseColor: blue

    - type: Box
      id: little-box
      visible: true
      position: [0, 7.5, -3.75]
      dimensions:
        length: 2.5
        width: 2.5
        height: 2.5
      material:
        baseColor: yellow
